package chatmap.domain;

/**
 * Describes whether a chat was imported from a source or generated by ChatMap.
 *
 * dbValue is the string persisted in chats.originatedBy and is stable forever;
 * the uppercase values are intentional -- they preserve what real databases
 * already contain. displayName is independently changeable UI text.
 *
 * fromDbValue is forgiving: an unrecognized or null stored value maps to
 * unknown rather than throwing, so older app versions can open databases
 * written by newer ones (same convention as {@link Source#fromDbValue}).
 */
public enum ChatOrigin {
    imported("IMPORTED", "Imported"),
    generated("GENERATED", "Generated"),
    unknown("UNKNOWN", "Unknown");

    private final String dbValue;
    private final String displayName;

    ChatOrigin(String dbValue, String displayName) {
        this.dbValue = dbValue;
        this.displayName = displayName;
    }

    public String dbValue() {
        return dbValue;
    }

    public String displayName() {
        return displayName;
    }

    public static ChatOrigin fromDbValue(String value) {
        for (ChatOrigin origin : values()) {
            if (origin.dbValue.equals(value)) {
                return origin;
            }
        }
        return unknown;
    }
}
